# ==============================================================================
# Auto-generated by generator.py based on SOP
# 因子类别：TrendMomentum
# 因子名称：MovingAverageBias
# ==============================================================================

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

BACKTEST_START_DATE = '20180101'
NORM_START_DATE = '20200101'
NORM_END_DATE = '20251231'

def _rollover_adjusted_turnover(pos_df, main_contract_df):
    prev_contract = main_contract_df.shift(1)
    is_rollover = (
        main_contract_df.ne(prev_contract)
        & main_contract_df.notna()
        & prev_contract.notna()
    ).reindex(columns=pos_df.columns, fill_value=False)
    prev_pos = pos_df.shift(1).fillna(0.0)
    normal_turnover   = pos_df.diff().fillna(0.0).abs()
    rollover_turnover = prev_pos.abs() + pos_df.abs()
    turnover_df = normal_turnover.where(~is_rollover, rollover_turnover)
    return turnover_df.sum(axis=1)

def calc_metrics(norm_daily_pnl, norm_pos_df, main_contract_df, trading_days_per_year=250):
    pnl = norm_daily_pnl.dropna()
    std = pnl.std()
    sharpe = pnl.mean() / std * (trading_days_per_year ** 0.5) if std != 0 else float('nan')
    gmv      = norm_pos_df.abs().sum(axis=1)
    turnover = _rollover_adjusted_turnover(norm_pos_df, main_contract_df)
    total_turnover = turnover.sum()
    holding_period = (gmv.sum() / total_turnover) * 2 if total_turnover != 0 else float('nan')
    pot = (pnl.sum() / total_turnover) * 10000 if total_turnover != 0 else float('nan')
    return sharpe, pot, holding_period

def main():
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    os.makedirs(os.path.join(BASE_DIR, 'Result'), exist_ok=True)
    marketDataPath = os.path.join(BASE_DIR, '../../main_contract/')
    infoPath = os.path.join(BASE_DIR, '../../Info.csv')

    info = pd.read_csv(infoPath, encoding='utf-8-sig')

    # 回测板块：仅测试Agriculture板块
    info = info[info['sector'].str.upper() == 'NONFERROUS']
    allowed_codes = ['CU.SHF', 'AL.SHF']
    valid_codes = [c for c in info['ts_code'] if c in allowed_codes]

    data = {}
    main_contracts = {}
    for ts_code in valid_codes:
        filepath = os.path.join(marketDataPath, f"{ts_code}.csv")
        if os.path.exists(filepath):
            df = pd.read_csv(filepath)
            if 'trade_date' in df.columns:
                df['trade_date'] = df['trade_date'].astype(str)
                df.set_index('trade_date', inplace=True)
                for col in ['open', 'high', 'low', 'close', 'adj_close', 'adj_open', 'adj_high', 'adj_low', 'vol', 'oi']:
                    if col in df.columns:
                        df[col] = pd.to_numeric(df[col], errors='coerce')
                data[ts_code] = df
                if "mapping_ts_code" in df.columns:
                    main_contracts[ts_code] = df["mapping_ts_code"]

    main_contract_df = pd.DataFrame(main_contracts)
    param_list = [{'N': 40}]
    
    results = []
    pnl_df_raw = pd.DataFrame()
    pnl_df_sm = pd.DataFrame()

    for param in param_list:
        N = param['N']
        
        pnl_raw_list = []
        pnl_sm_list = []
        to_raw_list = []
        to_sm_list = []
        pos_raw_param_list = []
        pnl_raw_param_list = []
        pos_sm_param_list = []
        pnl_sm_param_list = []
        
        for ts_code, df in data.items():
            raw_close = df['close']
            close = df['adj_close']
            open_p = df['adj_open']
            high = df['adj_high']
            low = df['adj_low']
            pre_close = close.shift(1)
            vol_ = df.get('vol', pd.Series(1, index=close.index))
            volume = vol_
            oi = df.get('oi', pd.Series(1, index=close.index))

            raw_sig = close / close.rolling(window=N).mean() - 1

            if not isinstance(raw_sig, pd.Series):
                raw_sig = pd.Series(raw_sig, index=close.index)
            raw_sig = raw_sig.fillna(0)
            sm_sig = np.sign(raw_sig)

            # Volatility scaling
            daily_ret = close.pct_change(fill_method=None)
            vol = daily_ret.rolling(20, min_periods=1).std().replace(0, np.nan)
            
            target_pos_raw = raw_sig / vol
            target_pos_sm = sm_sig / vol
            
            # Position smoothing EMA 10
            smoothed_pos_raw = target_pos_raw.ewm(span=10, min_periods=1).mean().fillna(0)
            smoothed_pos_sm = target_pos_sm.ewm(span=10, min_periods=1).mean().fillna(0)

            # PnL
            pnl_raw = smoothed_pos_raw.shift(1) * daily_ret
            pnl_sm = smoothed_pos_sm.shift(1) * daily_ret
            
            pnl_raw_list.append(pnl_raw)
            pnl_sm_list.append(pnl_sm)
            
            # Turnover
            is_rollover = (close / raw_close.replace(0, np.nan)).diff().abs() > 1e-5
            
            to_raw = smoothed_pos_raw.diff().abs()
            to_raw[is_rollover] = smoothed_pos_raw.shift(1).abs() + smoothed_pos_raw.abs()
            to_raw_list.append(to_raw.fillna(0))

            to_sm = smoothed_pos_sm.diff().abs()
            to_sm[is_rollover] = smoothed_pos_sm.shift(1).abs() + smoothed_pos_sm.abs()
            to_sm_list.append(to_sm.fillna(0))

            pos_raw_param_list.append(smoothed_pos_raw.rename(ts_code))
            pnl_raw_param_list.append((smoothed_pos_raw.shift(1).fillna(0) * daily_ret).rename(ts_code))
            pos_sm_param_list.append(smoothed_pos_sm.rename(ts_code))
            pnl_sm_param_list.append((smoothed_pos_sm.shift(1).fillna(0) * daily_ret).rename(ts_code))

        if not pnl_raw_list:
            continue
            
        
        param_str = str(param).replace(':', '').replace('{', '').replace('}', '').replace(' ', '').replace("'", "")
        
        pos_df_sm = pd.concat(pos_sm_param_list, axis=1).sort_index()
        pnl_df_sm = pd.concat(pnl_sm_param_list, axis=1).sort_index()
        daily_pnl = pnl_df_sm.sum(axis=1)
        if BACKTEST_START_DATE:
            pos_df_sm = pos_df_sm[pos_df_sm.index >= BACKTEST_START_DATE]
            pnl_df_sm = pnl_df_sm[pnl_df_sm.index >= BACKTEST_START_DATE]
            daily_pnl = daily_pnl[daily_pnl.index >= BACKTEST_START_DATE]

        pnl_for_scale = daily_pnl
        if NORM_START_DATE:
            pnl_for_scale = pnl_for_scale[pnl_for_scale.index >= NORM_START_DATE]
        if NORM_END_DATE:
            pnl_for_scale = pnl_for_scale[pnl_for_scale.index <= NORM_END_DATE]
        scale = pnl_for_scale.std()
        if scale == 0 or pd.isna(scale):
            scale = 1.0

        norm_pos_df_sm = pos_df_sm / scale
        norm_daily_pnl = daily_pnl / scale

        # Save files
        base_name = os.path.basename(__file__).replace('.py', '')
        out_pos = os.path.join(BASE_DIR, 'Result', f'{base_name}_norm_Position.csv')
        out_pnl = os.path.join(BASE_DIR, 'Result', f'{base_name}_norm_PnL.csv')
        out_plot = os.path.join(BASE_DIR, 'Result', f'{base_name}_cPnL.png')
        
        norm_pos_df_sm.to_csv(out_pos)
        norm_daily_pnl.to_frame(name='PnL').to_csv(out_pnl)
        
        import matplotlib.dates as mdates

        if 'norm_pos_df_sm' in locals():
            norm_pos_df = norm_pos_df_sm.copy()
        elif 'norm_pos_df_raw' in locals():
            norm_pos_df = norm_pos_df_raw.copy()
        else:
            raise ValueError("No norm pos df found")

        _mc_df = main_contract_df.reindex(index=norm_pos_df.index, columns=norm_pos_df.columns)
        sharpe, pot, hold = calc_metrics(norm_daily_pnl, norm_pos_df, _mc_df)
        plot_title = f"{base_name} {param_str} | Sharpe: {sharpe:.2f} | POT: {pot:.2f} | Hold: {hold:.1f}d"
        trade_dates = pd.to_datetime(norm_daily_pnl.index, format='%Y%m%d')
        cumulative_pnl = norm_daily_pnl.cumsum()
        
        fig, ax = plt.subplots(figsize=(14, 5))
        ax.plot(trade_dates, cumulative_pnl, linewidth=2, color='#1f77b4')
        ax.axhline(0, color='black', linewidth=0.6, linestyle='--')
        ax.set_title(plot_title)
        ax.set_ylabel('Cumulative PnL')
        ax.xaxis.set_major_locator(mdates.YearLocator())
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
        ax.set_xlim(left=trade_dates[0])
        fig.autofmt_xdate()
        plt.tight_layout()
        fig.savefig(out_plot, dpi=150)
        plt.close(fig)
        
        print(f"Generated normalized files for {param_str}")


if __name__ == "__main__":
    main()
