# ============================================================================== 
# Auto-generated by script
# 因子类别：Volume
# 因子名称：MFI
# ============================================================================== 

import pandas as pd
import numpy as np
import os


def _sector_prefix(sector_name: str) -> str:
    mapping = {
        'AGRICULTURE': 'Agriculture',
        'ENERGY': 'Energy',
        'FERROUS': 'Ferrous',
        'NONFERROUS': 'NonFerrous',
        'PRECIOUS': 'Precious',
    }
    return mapping.get(sector_name.upper(), sector_name.title())


def main():
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    marketDataPath = os.path.join(BASE_DIR, '../main_contract/')
    infoPath = os.path.join(BASE_DIR, '../Info.csv')

    info = pd.read_csv(infoPath, encoding='utf-8-sig')
    info['sector'] = info['sector'].astype(str)

    os.makedirs(os.path.join(BASE_DIR, '../Result'), exist_ok=True)

    # 回测板块：按主 sector 分别测试
    sector_list = ['AGRICULTURE', 'ENERGY', 'FERROUS', 'NONFERROUS', 'PRECIOUS']
    param_list = [{'N': 14}]

    all_results = []

    for sector_name in sector_list:
        sector_info = info[info['sector'].str.upper() == sector_name]
        valid_codes = sector_info['ts_code'].tolist()
        if not valid_codes:
            continue

        data = {}
        main_contracts = {}
        for ts_code in valid_codes:
            filepath = os.path.join(marketDataPath, f"{ts_code}.csv")
            if os.path.exists(filepath):
                df = pd.read_csv(filepath)
                if 'trade_date' in df.columns:
                    df['trade_date'] = df['trade_date'].astype(str)
                    df.set_index('trade_date', inplace=True)
                    for col in ['open', 'high', 'low', 'close', 'adj_close', 'adj_open', 'adj_high', 'adj_low', 'vol', 'oi']:
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors='coerce')
                    data[ts_code] = df
                    if 'mapping_ts_code' in df.columns:
                        main_contracts[ts_code] = df['mapping_ts_code']

        if not data:
            continue

        main_contract_df = pd.DataFrame(main_contracts)
        sector_prefix = _sector_prefix(sector_name)

        for param in param_list:
            N = param['N']

            pnl_raw_param_list = []
            pnl_sm_param_list = []
            to_raw_param_list = []
            to_sm_param_list = []
            pos_raw_param_list = []
            pos_sm_param_list = []

            for ts_code, df in data.items():
                raw_close = df['close'] if 'close' in df.columns else df['adj_close']
                close = df['adj_close']
                vol_ = df.get('vol', pd.Series(1, index=close.index))
                volume = vol_

                high = df['adj_high']
                low = df['adj_low']

                typical_price = (high + low + close) / 3.0
                raw_money_flow = typical_price * volume
                price_change = typical_price.diff()
                positive_flow = raw_money_flow.where(price_change > 0, 0.0)
                negative_flow = raw_money_flow.where(price_change < 0, 0.0)

                pos_sum = positive_flow.rolling(window=N, min_periods=1).sum()
                neg_sum = negative_flow.rolling(window=N, min_periods=1).sum()
                money_flow_ratio = pos_sum / (neg_sum + 1e-8)
                mfi = 100 - (100 / (1 + money_flow_ratio))
                raw_sig = ((mfi - 50) / 50).fillna(0)

                if not isinstance(raw_sig, pd.Series):
                    raw_sig = pd.Series(raw_sig, index=close.index)
                raw_sig = raw_sig.fillna(0)
                sm_sig = np.sign(raw_sig)

                daily_ret = close.pct_change(fill_method=None)
                vol = daily_ret.rolling(20, min_periods=1).std().replace(0, np.nan)

                target_pos_raw = raw_sig / vol
                target_pos_sm = sm_sig / vol

                smoothed_pos_raw = target_pos_raw.ewm(span=10, min_periods=1).mean().fillna(0)
                smoothed_pos_sm = target_pos_sm.ewm(span=10, min_periods=1).mean().fillna(0)

                pnl_raw = smoothed_pos_raw.shift(1) * daily_ret
                pnl_sm = smoothed_pos_sm.shift(1) * daily_ret

                pnl_raw_param_list.append(pnl_raw)
                pnl_sm_param_list.append(pnl_sm)

                is_rollover = (close / raw_close.replace(0, np.nan)).diff().abs() > 1e-5

                to_raw = smoothed_pos_raw.diff().abs()
                to_raw[is_rollover] = smoothed_pos_raw.shift(1).abs() + smoothed_pos_raw.abs()
                to_raw_param_list.append(to_raw.fillna(0))

                to_sm = smoothed_pos_sm.diff().abs()
                to_sm[is_rollover] = smoothed_pos_sm.shift(1).abs() + smoothed_pos_sm.abs()
                to_sm_param_list.append(to_sm.fillna(0))

                pos_raw_param_list.append(smoothed_pos_raw.rename(ts_code))
                pos_sm_param_list.append(smoothed_pos_sm.rename(ts_code))

            if not pnl_raw_param_list:
                continue

            param_str = str(param).replace(':', '').replace('{', '').replace('}', '').replace(' ', '').replace("'", '')

            pos_df_raw = pd.concat(pos_raw_param_list, axis=1).sort_index()
            pos_df_raw.to_csv(os.path.join(BASE_DIR, '../Result', f'{sector_prefix}_Volume_MFI_{param_str}_RAW_Position.csv'))

            pos_df_sm = pd.concat(pos_sm_param_list, axis=1).sort_index()
            pos_df_sm.to_csv(os.path.join(BASE_DIR, '../Result', f'{sector_prefix}_Volume_MFI_{param_str}_STATE_MACHINE_Position.csv'))

            df_pnl_raw = pd.concat(pnl_raw_param_list, axis=1).sort_index().sum(axis=1)
            sr_raw = df_pnl_raw.mean() / df_pnl_raw.std() * np.sqrt(252) if df_pnl_raw.std() > 0 else 0
            total_pnl_raw = df_pnl_raw.sum()
            total_to_raw = pd.concat(to_raw_param_list, axis=1).sort_index().sum(axis=1).sum()
            pot_raw = total_pnl_raw / (total_to_raw + 1e-9) * 10000

            df_pnl_sm = pd.concat(pnl_sm_param_list, axis=1).sort_index().sum(axis=1)
            sr_sm = df_pnl_sm.mean() / df_pnl_sm.std() * np.sqrt(252) if df_pnl_sm.std() > 0 else 0
            total_pnl_sm = df_pnl_sm.sum()
            total_to_sm = pd.concat(to_sm_param_list, axis=1).sort_index().sum(axis=1).sum()
            pot_sm = total_pnl_sm / (total_to_sm + 1e-9) * 10000

            all_results.append({
                'Sector': sector_prefix,
                'Factor': 'MFI',
                'Parameters': str(param),
                'Mode': 'RAW',
                'SharpRatio': round(sr_raw, 4),
                'POT': round(pot_raw, 4)
            })
            all_results.append({
                'Sector': sector_prefix,
                'Factor': 'MFI',
                'Parameters': str(param),
                'Mode': 'STATE_MACHINE',
                'SharpRatio': round(sr_sm, 4),
                'POT': round(pot_sm, 4)
            })

            out_path = os.path.join(BASE_DIR, '../Result', f'{sector_prefix}_Volume_MFI_BacktestResult.csv')
            pd.DataFrame([
                {
                    'Factor': 'MFI',
                    'Parameters': str(param),
                    'Mode': 'RAW',
                    'SharpRatio': round(sr_raw, 4),
                    'POT': round(pot_raw, 4)
                },
                {
                    'Factor': 'MFI',
                    'Parameters': str(param),
                    'Mode': 'STATE_MACHINE',
                    'SharpRatio': round(sr_sm, 4),
                    'POT': round(pot_sm, 4)
                },
            ]).to_csv(out_path, index=False)

            pnl_raw_path = os.path.join(BASE_DIR, '../Result', f'{sector_prefix}_Volume_MFI_PnL_RAW.csv')
            df_pnl_raw.to_frame(name='PnL').to_csv(pnl_raw_path)

            pnl_sm_path = os.path.join(BASE_DIR, '../Result', f'{sector_prefix}_Volume_MFI_PnL_SM.csv')
            df_pnl_sm.to_frame(name='PnL').to_csv(pnl_sm_path)

            print(f'{sector_prefix}_Volume_MFI Done. Saved to {out_path}')

    if all_results:
        pd.DataFrame(all_results).to_csv(os.path.join(BASE_DIR, '../Result', 'Volume_MFI_AllSectors_BacktestResult.csv'), index=False)


if __name__ == '__main__':
    main()