# ==============================================================================
# Auto-generated by script
# 因子类别：Microstructure
# 因子名称：Volume_MFI
# 回测板块：Energy
# 参数：N30
# 信号处理方式：zscore
# ==============================================================================

import importlib
import os
import sys

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

BACKTEST_START_DATE = '20180101'
NORM_START_DATE = '20200101'
NORM_END_DATE = '20251231'
FACTOR_NAME = 'Volume_MFI'
SECTOR = 'Energy'
PARAM = {'N': 30}
SIGNAL_METHOD = 'zscore'
ZSCORE_WINDOW = 60
ZSCORE_MIN_PERIODS = 20
TANH_SCALE = 1.0
POSITION_VOL_WINDOW = 20
POSITION_EWM_SPAN = 10


def _rollover_adjusted_turnover(pos_df, main_contract_df):
    prev_contract = main_contract_df.shift(1)
    is_rollover = (
        main_contract_df.ne(prev_contract)
        & main_contract_df.notna()
        & prev_contract.notna()
    ).reindex(columns=pos_df.columns, fill_value=False)
    prev_pos = pos_df.shift(1).fillna(0.0)
    normal_turnover = pos_df.diff().fillna(0.0).abs()
    rollover_turnover = prev_pos.abs() + pos_df.abs()
    turnover_df = normal_turnover.where(~is_rollover, rollover_turnover)
    return turnover_df.sum(axis=1)


def calc_metrics(norm_daily_pnl, norm_pos_df, main_contract_df, trading_days_per_year=250):
    pnl = norm_daily_pnl.dropna()
    std = pnl.std()
    sharpe = pnl.mean() / std * (trading_days_per_year ** 0.5) if std != 0 else float('nan')
    gmv = norm_pos_df.abs().sum(axis=1)
    turnover = _rollover_adjusted_turnover(norm_pos_df, main_contract_df)
    total_turnover = turnover.sum()
    holding_period = (gmv.sum() / total_turnover) * 2 if total_turnover != 0 else float('nan')
    pot = (pnl.sum() / total_turnover) * 10000 if total_turnover != 0 else float('nan')
    return sharpe, pot, holding_period


def state_machine_transform(raw):
    out = pd.DataFrame(index=raw.index, columns=raw.columns, dtype=float)
    for col in raw.columns:
        values = raw[col].to_numpy(dtype=float)
        states = np.zeros(values.shape[0], dtype=float)
        state = 0.0
        for i, x in enumerate(values):
            if np.isnan(x):
                states[i] = state
                continue
            if state == 0.0:
                if x > 0.0:
                    state = 1.0
                elif x < -0.0:
                    state = -1.0
            elif state > 0.0:
                if x < -0.0:
                    state = -1.0
                elif x < 0.0:
                    state = 0.0
            else:
                if x > 0.0:
                    state = 1.0
                elif x > -0.0:
                    state = 0.0
            states[i] = state
        out[col] = states
    return out


def zscore_transform(raw):
    rolling_mean = raw.rolling(window=ZSCORE_WINDOW, min_periods=ZSCORE_MIN_PERIODS).mean()
    rolling_std = raw.rolling(window=ZSCORE_WINDOW, min_periods=ZSCORE_MIN_PERIODS).std()
    z = (raw - rolling_mean) / rolling_std.replace(0.0, np.nan)
    return z.fillna(0.0).clip(lower=-3.0, upper=3.0)


def transform_signal(raw):
    if SIGNAL_METHOD == 'raw':
        return raw.fillna(0.0)
    if SIGNAL_METHOD == 'state_machine':
        return state_machine_transform(raw.fillna(0.0))
    if SIGNAL_METHOD == 'zscore':
        return zscore_transform(raw)
    if SIGNAL_METHOD == 'tanh':
        return np.tanh(raw.fillna(0.0) * TANH_SCALE)
    raise ValueError(f'Unknown SIGNAL_METHOD: {SIGNAL_METHOD}')


def _load_factor_module(base_dir):
    factor_dir = os.path.abspath(os.path.join(base_dir, '..', '..', 'Factor'))
    if factor_dir not in sys.path:
        sys.path.insert(0, factor_dir)
    return importlib.import_module(FACTOR_NAME)


def _load_market_data(market_data_path, ts_code):
    filepath = os.path.join(market_data_path, f'{ts_code}.csv')
    if not os.path.exists(filepath):
        return None
    df = pd.read_csv(filepath)
    if 'trade_date' not in df.columns:
        return None
    df['trade_date'] = df['trade_date'].astype(str)
    df.set_index('trade_date', inplace=True)
    for col in ['open', 'high', 'low', 'close', 'adj_close', 'adj_open', 'adj_high', 'adj_low', 'vol', 'oi']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    return df


def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    result_dir = os.path.join(base_dir, 'Result')
    os.makedirs(result_dir, exist_ok=True)
    market_data_path = os.path.join(base_dir, '..', '..', 'main_contract')
    info_path = os.path.join(base_dir, '..', '..', 'Info.csv')

    factor_module = _load_factor_module(base_dir)
    info = pd.read_csv(info_path, encoding='utf-8-sig')
    info = info[info['sector'].astype(str).str.upper() == SECTOR.upper()]
    valid_codes = sorted(info['ts_code'].astype(str).tolist())

    raw_series = []
    returns = []
    main_contracts = {}
    for ts_code in valid_codes:
        df = _load_market_data(market_data_path, ts_code)
        if df is None:
            continue
        raw_sig = factor_module._calc_signal(df, PARAM['N'])
        if not isinstance(raw_sig, pd.Series):
            raw_sig = pd.Series(raw_sig, index=df.index)
        raw_series.append(raw_sig.rename(ts_code))
        close = pd.to_numeric(df['adj_close'], errors='coerce')
        returns.append(close.pct_change(fill_method=None).rename(ts_code))
        if 'mapping_ts_code' in df.columns:
            main_contracts[ts_code] = df['mapping_ts_code']

    if not raw_series:
        print(f'Skip {FACTOR_NAME} {SECTOR} {PARAM}: no valid data')
        return

    raw_df = pd.concat(raw_series, axis=1).sort_index().fillna(0.0).astype(float)
    raw_df = raw_df[raw_df.index >= BACKTEST_START_DATE]
    signal_df = transform_signal(raw_df).fillna(0.0).astype(float)

    ret_df = pd.concat(returns, axis=1).sort_index().reindex(index=signal_df.index, columns=signal_df.columns)
    vol_df = ret_df.rolling(POSITION_VOL_WINDOW, min_periods=1).std().replace(0.0, np.nan)
    target_pos = signal_df / vol_df
    pos_df = target_pos.ewm(span=POSITION_EWM_SPAN, min_periods=1).mean().replace([np.inf, -np.inf], np.nan).fillna(0.0)
    pnl_df = pos_df.shift(1).fillna(0.0) * ret_df
    daily_pnl = pnl_df.sum(axis=1).fillna(0.0)

    pnl_for_scale = daily_pnl.copy()
    if NORM_START_DATE:
        pnl_for_scale = pnl_for_scale[pnl_for_scale.index >= NORM_START_DATE]
    if NORM_END_DATE:
        pnl_for_scale = pnl_for_scale[pnl_for_scale.index <= NORM_END_DATE]
    scale = pnl_for_scale.std()
    if scale == 0 or pd.isna(scale):
        scale = 1.0

    norm_pos_df = pos_df / scale
    norm_daily_pnl = daily_pnl / scale

    base_name = os.path.basename(__file__).replace('.py', '')
    out_pos = os.path.join(result_dir, f'{base_name}_norm_Position.csv')
    out_pnl = os.path.join(result_dir, f'{base_name}_norm_PnL.csv')
    out_gmv = os.path.join(result_dir, f'{base_name}_GMV.csv')
    out_plot = os.path.join(result_dir, f'{base_name}_cPnL.png')

    norm_pos_df.to_csv(out_pos, encoding='utf-8-sig')
    norm_daily_pnl.to_frame(name='PnL').to_csv(out_pnl, encoding='utf-8-sig')
    norm_pos_df.abs().sum(axis=1).to_frame(name='GMV').to_csv(out_gmv, encoding='utf-8-sig')

    main_contract_df = pd.DataFrame(main_contracts).reindex(index=norm_pos_df.index, columns=norm_pos_df.columns)
    sharpe, pot, hold = calc_metrics(norm_daily_pnl, norm_pos_df, main_contract_df)
    trade_dates = pd.to_datetime(norm_daily_pnl.index, format='%Y%m%d')
    cumulative_pnl = norm_daily_pnl.cumsum()
    plot_title = f'{base_name} {SIGNAL_METHOD} {PARAM} | Sharpe: {sharpe:.2f} | POT: {pot:.2f} | Hold: {hold:.1f}d'

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.plot(trade_dates, cumulative_pnl, linewidth=2, color='#1f77b4')
    ax.axhline(0, color='black', linewidth=0.6, linestyle='--')
    ax.set_title(plot_title)
    ax.set_ylabel('Cumulative PnL')
    ax.xaxis.set_major_locator(mdates.YearLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    ax.set_xlim(left=trade_dates[0])
    fig.autofmt_xdate()
    plt.tight_layout()
    fig.savefig(out_plot, dpi=150)
    plt.close(fig)

    print(f'Generated normalized files for {base_name}; signal={SIGNAL_METHOD}; scale={scale}')


if __name__ == '__main__':
    main()
