import os, re, glob
import pandas as pd
import numpy as np

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FACTOR_DIR = os.path.join(BASE_DIR, '../Factor')
STRATEGY_DIR = os.path.join(BASE_DIR, '../Strategy')
RESULT_DIR = os.path.join(BASE_DIR, '../Result')

os.makedirs(STRATEGY_DIR, exist_ok=True)

TEMPLATE = '''# ==============================================================================
# Auto-generated by generator.py based on SOP
# 因子类别：{category}
# 因子名称：{factor_name}
# ==============================================================================

import pandas as pd
import numpy as np
import os

def main():
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    marketDataPath = os.path.join(BASE_DIR, '../main_contract/')
    infoPath = os.path.join(BASE_DIR, '../Info.csv')

    info = pd.read_csv(infoPath, encoding='utf-8-sig')

    # 回测板块：仅测试Agriculture板块
    info = info[info['sector'].str.upper() == 'AGRICULTURE']
    exclude_list = ['A.DCE', 'B.DCE', 'C.DCE', 'CS.DCE', 'JD.DCE', 'LH.DCE', 'AP.ZCE', 'UR.ZCE', 'M.DCE', 'Y.DCE', 'P.DCE', 'OI.ZCE', 'RM.ZCE']
    valid_codes = info[~info['ts_code'].isin(exclude_list)]['ts_code'].tolist()

    data = {}
    for ts_code in valid_codes:
        filepath = os.path.join(marketDataPath, f"{ts_code}.csv")
        if os.path.exists(filepath):
            df = pd.read_csv(filepath)
            if 'trade_date' in df.columns:
                df['trade_date'] = df['trade_date'].astype(str)
                df.set_index('trade_date', inplace=True)
                for col in ['open', 'high', 'low', 'close', 'adj_close', 'adj_open', 'adj_high', 'adj_low', 'vol', 'oi']:
                    if col in df.columns:
                        df[col] = pd.to_numeric(df[col], errors='coerce')
                data[ts_code] = df

    {param_loop}
    
    results = []
    pnl_df_raw = pd.DataFrame()
    pnl_df_sm = pd.DataFrame()

    for param in param_list:
        {param_unpack}
        
        pnl_raw_list = []
        pnl_sm_list = []
        to_raw_list = []
        to_sm_list = []
        pos_raw_param_list = []
        pos_sm_param_list = []
        
        for ts_code, df in data.items():
            raw_close = df['close']
            close = df['adj_close']
            open_p = df['adj_open']
            high = df['adj_high']
            low = df['adj_low']
            pre_close = close.shift(1)
            vol_ = df.get('vol', pd.Series(1, index=close.index))
            volume = vol_
            oi = df.get('oi', pd.Series(1, index=close.index))

{factor_logic}

            if not isinstance(raw_sig, pd.Series):
                raw_sig = pd.Series(raw_sig, index=close.index)
            raw_sig = raw_sig.fillna(0)
            sm_sig = np.sign(raw_sig)

            # Volatility scaling
            daily_ret = close.pct_change(fill_method=None)
            vol = daily_ret.rolling(20, min_periods=1).std().replace(0, np.nan)
            
            target_pos_raw = raw_sig / vol
            target_pos_sm = sm_sig / vol
            
            # Position smoothing EMA 10
            smoothed_pos_raw = target_pos_raw.ewm(span=10, min_periods=1).mean().fillna(0)
            smoothed_pos_sm = target_pos_sm.ewm(span=10, min_periods=1).mean().fillna(0)

            # PnL
            pnl_raw = smoothed_pos_raw.shift(1) * daily_ret
            pnl_sm = smoothed_pos_sm.shift(1) * daily_ret
            
            pnl_raw_list.append(pnl_raw)
            pnl_sm_list.append(pnl_sm)
            
            # Turnover
            is_rollover = (close / raw_close.replace(0, np.nan)).diff().abs() > 1e-5
            
            to_raw = smoothed_pos_raw.diff().abs()
            to_raw[is_rollover] = smoothed_pos_raw.shift(1).abs() + smoothed_pos_raw.abs()
            to_raw_list.append(to_raw.fillna(0))

            to_sm = smoothed_pos_sm.diff().abs()
            to_sm[is_rollover] = smoothed_pos_sm.shift(1).abs() + smoothed_pos_sm.abs()
            to_sm_list.append(to_sm.fillna(0))

            pos_raw_param_list.append(smoothed_pos_raw.rename(ts_code))
            pos_sm_param_list.append(smoothed_pos_sm.rename(ts_code))

        if not pnl_raw_list:
            continue
            
        param_str = str(param).replace(':', '').replace('{', '').replace('}', '').replace(' ', '').replace("'", "")
        
        pos_df_raw = pd.concat(pos_raw_param_list, axis=1).sort_index()
        pos_df_raw.to_csv(os.path.join(BASE_DIR, '../Result', f'AgriSelect_{category}_{factor_name}_{param_str}_RAW_Position.csv'))
        
        pos_df_sm = pd.concat(pos_sm_param_list, axis=1).sort_index()
        pos_df_sm.to_csv(os.path.join(BASE_DIR, '../Result', f'AgriSelect_{category}_{factor_name}_{param_str}_STATE_MACHINE_Position.csv'))

        df_pnl_raw = pd.concat(pnl_raw_list, axis=1).sort_index().sum(axis=1)
        sr_raw = df_pnl_raw.mean() / df_pnl_raw.std() * np.sqrt(252) if df_pnl_raw.std() > 0 else 0
        total_pnl_raw = df_pnl_raw.sum()
        total_to_raw = pd.concat(to_raw_list, axis=1).sort_index().sum(axis=1).sum()
        pot_raw = total_pnl_raw / (total_to_raw + 1e-9) * 10000
        pnl_df_raw[str(param)] = df_pnl_raw

        df_pnl_sm = pd.concat(pnl_sm_list, axis=1).sort_index().sum(axis=1)
        sr_sm = df_pnl_sm.mean() / df_pnl_sm.std() * np.sqrt(252) if df_pnl_sm.std() > 0 else 0
        total_pnl_sm = df_pnl_sm.sum()
        total_to_sm = pd.concat(to_sm_list, axis=1).sort_index().sum(axis=1).sum()
        pot_sm = total_pnl_sm / (total_to_sm + 1e-9) * 10000
        pnl_df_sm[str(param)] = df_pnl_sm

        results.append({
            'Factor': '{factor_name}',
            'Parameters': str(param),
            'Mode': 'RAW',
            'SharpRatio': round(sr_raw, 4),
            'POT': round(pot_raw, 4)
        })
        results.append({
            'Factor': '{factor_name}',
            'Parameters': str(param),
            'Mode': 'STATE_MACHINE',
            'SharpRatio': round(sr_sm, 4),
            'POT': round(pot_sm, 4)
        })
        
    if results:
        res_df = pd.DataFrame(results)
        out_path = os.path.join(BASE_DIR, '../Result', f'AgriSelect_{category}_{factor_name}_BacktestResult.csv')
        res_df.to_csv(out_path, index=False)
        
        pnl_raw_path = os.path.join(BASE_DIR, '../Result', f'AgriSelect_{category}_{factor_name}_PnL_RAW.csv')
        pnl_df_raw.sort_index().to_csv(pnl_raw_path)
        
        pnl_sm_path = os.path.join(BASE_DIR, '../Result', f'AgriSelect_{category}_{factor_name}_PnL_SM.csv')
        pnl_df_sm.sort_index().to_csv(pnl_sm_path)
        
        print(f"AgriSelect_{category}_{factor_name} Done. Saved to {out_path}")
    else:
        print(f"AgriSelect_{category}_{factor_name} No results.")

if __name__ == "__main__":
    main()
'''

def main():
    for f_path in glob.glob(os.path.join(FACTOR_DIR, '*.py')):
        name = os.path.basename(f_path).replace('.py', '')
        if '_' not in name: continue
        category, factor_name = name.split('_', 1)
        
        with open(f_path, 'r', encoding='utf-8') as f:
            content = f.read()

        param_match = re.search(r'PARAM_LIST\s*=\s*(\[.*?\])', content, re.DOTALL)
        if param_match:
            param_list_str = param_match.group(1).replace('\\n', ' ')
            param_loop = f"param_list = {param_list_str}"
            vars_match = re.findall(r"(\w+)\s*=\s*param\['(\w+)'\]", content)
            if vars_match:
                param_unpack = '\n        '.join([f"{v[0]} = param['{v[1]}']" for v in vars_match])
            else:
                if 'MACD' in factor_name:
                    param_unpack = "fast_n = param['fast_n']\n        slow_n = param['slow_n']\n        signal_n = param['signal_n']"
                else:
                    param_unpack = "fast_n = param['fast_n']\n        slow_n = param['slow_n']"
        else:
            param_loop = "param_list = [{'N': n} for n in [10, 20, 30, 40, 50, 60]]"
            param_unpack = "N = param['N']"

        logic_match = re.search(r'# ---\s*因子计算逻辑\s*---(.*?)# --------------------', content, re.DOTALL)
        if not logic_match:
            logic_match = re.search(r'# --- .*? ---(.*?)# --------------------', content, re.DOTALL)
            
        if logic_match:
            logic_str = logic_match.group(1)
            logic_lines = ["            " + line.strip() for line in logic_str.split('\n') if line.strip()]
            logic_indented = '\n'.join(logic_lines)
            
            logic_indented = re.sub(r'\bsignal\b', 'raw_sig', logic_indented)
            logic_indented = logic_indented.replace('.apply(lambda x: np.sign(x) if pd.notna(x) else np.nan)', '')
        else:
            print(f"Warning: No logic found in {name}")
            continue

        script_content = TEMPLATE.replace('{category}', category) \
                                 .replace('{factor_name}', factor_name) \
                                 .replace('{param_loop}', param_loop) \
                                 .replace('{param_unpack}', param_unpack) \
                                 .replace('{factor_logic}', logic_indented)

        strat_path = os.path.join(STRATEGY_DIR, os.path.basename(f_path))
        with open(strat_path, 'w', encoding='utf-8') as f:
            f.write(script_content)

    print("All strategy scripts generated. Beginning execution...\n")

    import subprocess
    scripts = [f for f in glob.glob(os.path.join(STRATEGY_DIR, '*.py')) if not f.endswith('Template.py') and not os.path.basename(f).startswith('generator') and not f.endswith('run_strategies.py')]
    for s in scripts:
        print(f"Running {os.path.basename(s)}...")
        subprocess.run(['C:/Users/liukaicheng/anaconda3/python.exe', s])
    print("All strategies executed.")

if __name__ == "__main__":
    main()
